using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using System.Windows.Forms;
using System.Configuration;
using System.ComponentModel;
using System.Reflection;
namespace PlayLogger
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            System.Windows.Application.Current.DispatcherUnhandledException += Current_DispatcherUnhandledException;
            this.DataContext = new MainViewModel();

            Assembly assembly = Assembly.GetExecutingAssembly();
            VersionTB.Text = string.Format("Version {0}",assembly.GetName().Version.ToString());
        }

        private void Current_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            MainViewModel.LogException(e.Exception);
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {

            // Load data by setting the CollectionViewSource.Source property:
            // songInfoViewSource.Source = [generic data source]

            //loadDGData();
        }


        private void BrowseButton_Click(object sender, RoutedEventArgs e)
        {
            using (var dialog = new FolderBrowserDialog())
            {
                DialogResult result = dialog.ShowDialog();
                if (result == System.Windows.Forms.DialogResult.OK)
                {
                    LastPlayDirTB.Text = dialog.SelectedPath;
                }
            }
        }

        int lastColIndex = -1;
        private void songInfoDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (hideColumn((PropertyDescriptor)e.PropertyDescriptor))
            {
                e.Cancel = true;
            }
            else
            {
                e.Column.DisplayIndex = ++lastColIndex;
            }
        }

        private bool hideColumn(PropertyDescriptor p)
        {
            bool hide = p.Attributes.OfType<HideFromDGAttribute>().Any();
            return hide;
        }
        private void songInfoDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var field in DbHandler.SongFields)
            {

                DataGridTextColumn textColumn = new DataGridTextColumn();
                textColumn.Header = field;
                textColumn.Binding = new System.Windows.Data.Binding(string.Format("Fields[{0}]", field));

                var existingCols = songInfoDataGrid.Columns.Where((col) => (string)col.Header == field);
                if (!existingCols.Any())
                {
                    songInfoDataGrid.Columns.Add(textColumn);
                }
            }
            lastColIndex = -1;
        }

        private void UpdateButton_Click(object sender, RoutedEventArgs e)
        {
            ((MainViewModel)this.DataContext).Update();
        }

        private void ToggleMonitorButton_Click(object sender, RoutedEventArgs e)
        {
            ((MainViewModel)this.DataContext).ToggleXmlDirMonitor();
        }
    }
}
