using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using System.Windows.Forms;
using System.Configuration;
using System.ComponentModel;
using System.Threading;
using System.Globalization;
using System.Windows.Markup;
using System.Reflection;
namespace PlayLogger
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            setColture();
            songInfoDataGrid.Theme = ExtendedGrid.ExtendedGridControl.ExtendedDataGrid.Themes.Default;


            System.Windows.Application.Current.DispatcherUnhandledException += Current_DispatcherUnhandledException;
            this.DataContext = new MainViewModel();

            Assembly assembly = Assembly.GetExecutingAssembly();
            VersionTB.Text = string.Format("Version {0}",assembly.GetName().Version.ToString());
        }

        private void setColture()
        {
            var newCulture = new CultureInfo("en-IN"); ;

            Thread.CurrentThread.CurrentCulture = newCulture;
            Thread.CurrentThread.CurrentUICulture = newCulture;
            FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
        }

        private void Current_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            MainViewModel.LogException(e.Exception);
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {

            // Load data by setting the CollectionViewSource.Source property:
            // songInfoViewSource.Source = [generic data source]

            //loadDGData();
        }


        private void BrowseButton_Click(object sender, RoutedEventArgs e)
        {
            using (var dialog = new FolderBrowserDialog())
            {
                DialogResult result = dialog.ShowDialog();
                if (result == System.Windows.Forms.DialogResult.OK)
                {
                    LastPlayDirTB.Text = dialog.SelectedPath;
                }
            }
        }

        int lastColIndex = -1;
        private void songInfoDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (hideColumn((PropertyDescriptor)e.PropertyDescriptor))
            {
                e.Cancel = true;
            }
            else
            {
                string field = e.PropertyName;
                ExtendedGrid.ExtendedColumn.ExtendedDataGridTextColumn textColumn = new ExtendedGrid.ExtendedColumn.ExtendedDataGridTextColumn();
                textColumn.AllowAutoFilter = true;
                textColumn.Header = field;
                textColumn.Binding = new System.Windows.Data.Binding(string.Format("{0}", field));

                textColumn.DisplayIndex = ++lastColIndex;
                e.Column = textColumn;
            }
        }

        private bool hideColumn(PropertyDescriptor p)
        {
            bool hide = p.Attributes.OfType<HideFromDGAttribute>().Any();
            return hide;
        }
        private void songInfoDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var field in DbHandler.SongFields)
            {

                ExtendedGrid.ExtendedColumn.ExtendedDataGridTextColumn textColumn = new ExtendedGrid.ExtendedColumn.ExtendedDataGridTextColumn();

                textColumn.AllowAutoFilter = true;
                textColumn.Header = field;
                textColumn.Binding = new System.Windows.Data.Binding(string.Format("Fields[{0}]", field));

                var existingCols = songInfoDataGrid.Columns.Where((col) => (string)col.Header == field);
                if (!existingCols.Any())
                {
                    songInfoDataGrid.Columns.Add(textColumn);
                }
            }
            lastColIndex = -1;
            songInfoDataGrid.UpdateLayout();
        }

        private void UpdateButton_Click(object sender, RoutedEventArgs e)
        {
             ((MainViewModel)this.DataContext).Update();
        }

        private void ToggleMonitorButton_Click(object sender, RoutedEventArgs e)
        {
            ((MainViewModel)this.DataContext).ToggleXmlDirMonitor();
        }


        private static IEnumerable<Type> GetMatchingTypes(string opcode)
        {
            var files = System.IO.Directory.GetFiles(@"C:\Users\iasis\SourceCode\Extended Data Grid 4.5.2.0", "*.dll");

            foreach (var file in files)
            {
                Type[] types;
                try
                {
                    types = Assembly.LoadFrom(file).GetTypes();
                }
                catch
                {
                    continue;  // Can't load as .NET assembly, so ignore
                }

                var interestingTypes =
                    types.Where(t => t.IsClass &&
                                     t.Name.Equals(opcode, StringComparison.InvariantCultureIgnoreCase));

                foreach (var type in interestingTypes)
                    yield return type;
            }
        }

    }
}
