using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using System.Windows.Forms;
using System.Configuration;
using System.ComponentModel;
using System.Threading;
using System.Globalization;
using System.Windows.Markup;
using System.Reflection;
namespace PlayLogger
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            setColture();
            songInfoDataGrid.Theme = ExtendedGrid.ExtendedGridControl.ExtendedDataGrid.Themes.Office2007Blue;

            System.Windows.Application.Current.DispatcherUnhandledException += Current_DispatcherUnhandledException;
            this.DataContext = MainViewModel.Instance;

            Assembly assembly = Assembly.GetExecutingAssembly();
            var version = assembly.GetName().Version;
            VersionTB.Text = string.Format("Version {0}.{1}.{2}", version.Major, version.Minor, version.Build);


            //System.Windows.Application.Current.Activated += (o, e) => { };
            //System.Windows.Application.Current.Deactivated += (o, e) => { settingsPopup.IsOpen = false; };
        }


        private void setColture()
        {
            var newCulture = new CultureInfo("en-IN"); ;

            Thread.CurrentThread.CurrentCulture = newCulture;
            Thread.CurrentThread.CurrentUICulture = newCulture;
            FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
        }

        private void Current_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            MainViewModel.LogException(e.Exception);
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {

            // Load data by setting the CollectionViewSource.Source property:
            // songInfoViewSource.Source = [generic data source]

            //loadDGData();
        }



        int lastColIndex = -1;
        private void songInfoDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (hideColumn((PropertyDescriptor)e.PropertyDescriptor))
            {
                e.Cancel = true;
            }
            else
            {
                string field = e.PropertyName;
                ExtendedGrid.ExtendedColumn.ExtendedDataGridTextColumn textColumn = new ExtendedGrid.ExtendedColumn.ExtendedDataGridTextColumn();
                textColumn.AllowAutoFilter = true;
                textColumn.Header = getColumnHeader(field);
                textColumn.Binding = new System.Windows.Data.Binding(string.Format("{0}", field));

                textColumn.DisplayIndex = ++lastColIndex;
                e.Column = textColumn;
            }
        }
        private void songInfoDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //addExtendedPropsColumns();
            lastColIndex = -1;
            songInfoDataGrid.UpdateLayout();

            setDefaults();
        }

        private string getColumnHeader(string field)
        {
            string res = field;
            MainViewModel vm = this.DataContext as MainViewModel;
            if (vm != null && vm.ColumnHeaders.ContainsKey(field))
            {
                res = vm.ColumnHeaders[field];
            }
            return res;
        }

        private bool hideColumn(PropertyDescriptor p)
        {
            bool hide = p.Attributes.OfType<HideFromDGAttribute>().Any();
            return hide;
        }
                
        private void setDefaults()
        {
            if (!isDefaultsSet)
            {
                setDefaultColOrder();
                setDummySort();
                isDefaultsSet = true;
            }
        }

        private void setDefaultColOrder()
        {
            var cols = songInfoDataGrid.Columns;
            var colMap = ((MainViewModel)this.DataContext).InitalColumnOrderMap;
            foreach (var col in cols)
            {
                string colname = col.SortMemberPath;
                if (colMap.ContainsKey(colname))
                {
                    col.DisplayIndex = colMap[colname];
                }
            }
        }


        private bool isDefaultsSet = false;
        private void setDummySort()
        {
            Action setSort = () =>
            {
                DataGridColumn col;
                col = songInfoDataGrid.Columns.FirstOrDefault(c => { return c.SortMemberPath == "PlayTime"; });
                if (col != null)
                {
                    col.SortDirection = ListSortDirection.Descending;
                }
            };

            if (songInfoDataGrid.ColumnInfo != null)
            {
                var colInfo = songInfoDataGrid.ColumnInfo.Where(ci => ci.SortDirection != null);
                if (!colInfo.Any())
                {
                    setSort();
                }
            }
            else
            {
                setSort();
            }
        }

        private void UpdateButton_Click(object sender, RoutedEventArgs e)
        {
            ((MainViewModel)this.DataContext).Update();
        }




        private static IEnumerable<Type> GetMatchingTypes(string opcode)
        {
            var files = System.IO.Directory.GetFiles(@"C:\Users\iasis\SourceCode\Extended Data Grid 4.5.2.0", "*.dll");

            foreach (var file in files)
            {
                Type[] types;
                try
                {
                    types = Assembly.LoadFrom(file).GetTypes();
                }
                catch
                {
                    continue;  // Can't load as .NET assembly, so ignore
                }

                var interestingTypes =
                    types.Where(t => t.IsClass &&
                                     t.Name.Equals(opcode, StringComparison.InvariantCultureIgnoreCase));

                foreach (var type in interestingTypes)
                    yield return type;
            }
        }

        private void exportXlsBtn_Click(object sender, RoutedEventArgs e)
        {
            using (var dialog = new SaveFileDialog())
            {
                dialog.Filter = "Excel Worksheet (*.xlsx)|*.xlsx";
                DialogResult result = dialog.ShowDialog();
                if (result == System.Windows.Forms.DialogResult.OK)
                {
                    string filepath = dialog.FileName;
                    songInfoDataGrid.ExportToExcel(this.Title, filepath, true);
                }
            }
        }

        private void showSettingsPage_Click(object sender, RoutedEventArgs e)
        {
            var settingsPage = new SettingsPopup();
            settingsPage.DataContext = this.DataContext;

            var window = new Window() 
            {
                Owner = this,
                FlowDirection = this.FlowDirection,
                Content = settingsPage,
                WindowStyle=System.Windows.WindowStyle.ToolWindow,
                ResizeMode = System.Windows.ResizeMode.NoResize,
                SizeToContent = System.Windows.SizeToContent.WidthAndHeight,
                WindowStartupLocation = System.Windows.WindowStartupLocation.CenterOwner,
                ShowInTaskbar = false,
                Title = "הגדרות"
            };
            window.ShowDialog();
        }

        private async void updateLastPlayedBtn_Click(object sender, RoutedEventArgs e)
        {
            var VM = ((MainViewModel)this.DataContext);

            if (VM.IsLoading || VM.SongsInfo == null)
                return;

            var places = VM.SongsInfo.Select(s => s.PlayLocation).Distinct().Where(p => p != VM.Settings.PlayLocation);
            var dialog = new LastPlayedUpdateDialog(places)
            {
                Owner = this,
                FlowDirection = this.FlowDirection,
                WindowStyle = System.Windows.WindowStyle.ToolWindow,
                ResizeMode = System.Windows.ResizeMode.NoResize,
                SizeToContent = System.Windows.SizeToContent.WidthAndHeight,
                WindowStartupLocation = System.Windows.WindowStartupLocation.CenterOwner,
                ShowInTaskbar = false,
                Title = "עדכון נוגן לאחרונה"
            };
            dialog.ShowDialog();

            if (dialog.Places != null && dialog.Places.Count > 0)
            {
                var songsToUpdate = VM.SongsInfo.Where(s => dialog.Places.Contains(s.PlayLocation))
                                                .GroupBy(s => s.Id)
                                                .Select(g => g.OrderByDescending(s => s.PlayTime).First());

                await VM.UpdateLastPlayedOnAmpsDB(songsToUpdate);
            }
        }
    }
}
